export const theme = {
  colors: {
    background: '#F4F3F0',
    backgroundStrong: '#ECE9E4',
    surface: '#FFFFFF',
    surfaceMuted: '#F7F6F3',
    primary: '#B20000',
    primaryStrong: '#780000',
    primarySoft: '#F5D8D8',
    secondary: '#1C1C1C',
    secondarySoft: '#E8E8E8',
    accent: '#666666',
    accentSoft: '#EFEFEF',
    text: '#171717',
    textMuted: '#5E5E5E',
    textOnPrimary: '#FFFFFF',
    border: '#D7D2CC',
    danger: '#C44949',
    dangerSoft: '#FBE8E8',
    success: '#266A4A',
    successSoft: '#E5F6F0',
  },
  spacing: {
    xxs: 4,
    xs: 6,
    sm: 10,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 40,
  },
  radius: {
    sm: 10,
    md: 16,
    lg: 24,
    xl: 32,
    pill: 999,
  },
  typography: {
    caption: 12,
    body: 14,
    bodyLarge: 16,
    title: 22,
    headline: 30,
  },
  fonts: {
    body: 'NotoSans_400Regular',
    bodyMedium: 'NotoSans_500Medium',
    bodySemiBold: 'NotoSans_600SemiBold',
    bodyBold: 'NotoSans_700Bold',
    headingBold: 'Raleway_700Bold',
    headingExtraBold: 'Raleway_800ExtraBold',
  },
} as const;

export type AppTheme = typeof theme;
